### PR TITLE
Bindgen into build.rs

### PR DESCRIPTION
**Pull request by mdaverde**
Hello!

In efforts to generate bindings against the latest libbpf, I ran into duplicate definitions causing issues which then led to looking into configuring bindgen.

With the end goal of being able to configure bindgen for future issues, this brings bindgen into the build.rs as well as updating the bindgen crate dependency itself. You can see the resulting bindings.rs is minimally changed.

It seems like in the initial commits of this project we originally had bindgen in build.rs but I couldn't figure out from the commits the reason why we moved it out. 

You can see my work on updating libbpf-sys (with possible bindgen configurations) in [this commit](https://github.com/mdaverde/libbpf-sys/commit/9b8bf368b6469f34bce956255bc97f8f5d3343b3).

### CODE REVIEW

**Review by anakryiko — APPROVED** [review]
LGTM!

**Comment by rsdy** [comment]
It would be super helpful for [redbpf](https://github.com/foniod/redbpf) to include `vdprintf` in the allowlist, so it saves us some [hacks](https://github.com/foniod/redbpf/pull/278/commits/6b47c284fabc7b92c468c488d6c5dc67091cbb4d).

**Comment by alexforster** [comment]
> It would be super helpful for [redbpf](https://github.com/foniod/redbpf) to include vdprintf in the allowlist, so it saves us some [hacks](https://github.com/foniod/redbpf/pull/278/commits/6b47c284fabc7b92c468c488d6c5dc67091cbb4d).

I'll also add `vdprintf` and then cut a new `0.6.x` release. Still working on getting 0.7 generating properly...

**Comment by alexforster** [comment]
@mdaverde [this commit](https://github.com/mdaverde/libbpf-sys/commit/9b8bf368b6469f34bce956255bc97f8f5d3343b3) that you reference is interesting. Does this successfully allow you to generate bindings for `libbpf v0.7.0`?

**Comment by mdaverde** [comment]
That commit allowed me to generate bindings for libbpf at commit [`67a4b146434`](https://github.com/libbpf/libbpf/commit/67a4b1464349345e483df26ed93f8d388a60cee1) which was after the `v0.7.0` release so it should work. I can send a PR soon

**Pull request merged**
