### PR TITLE
Update libbpf to 1.4.5

### PR DESCRIPTION
**Pull request by danielocfb**
Update the libbpf submodule to version 1.4.5 to get a bunch of bug fixes.

### CODE REVIEW

**Review by anakryiko — APPROVED** [review]

**Comment by danielocfb** [comment]
Can this change please be merged and a new release cut?

**Comment by danielocfb** [comment]
@alexforster ^^^

**Comment by alexforster** [comment]
Not a single bindgen change?

**Comment by alexforster** [comment]
Pushed to crates.io

**Comment by danielocfb** [comment]
> Pushed to crates.io

Thank you!

**Pull request merged**
