### PR TITLE
update libbpf to latest release v1.3

### PR DESCRIPTION
**Pull request by syogaraj**

### CODE REVIEW

**Comment by syogaraj** [comment]
@alexforster any updates on this, please?

**Comment by alexforster** [comment]
Sorry for the delay. Looks good. I'll cut a release for it soon.

**Comment by anakryiko** [comment]
> Sorry for the delay. Looks good. I'll cut a release for it soon.

friednly ping, @alexforster. People start to ask for libbpf v1.3-based release of libbpf-sys (and libbpf-rs), can you please prioritize publishing a new release? Thanks!

**Comment by alexforster** [comment]
Let me do that right now before it falls back into the memory hole.

**Comment by alexforster** [comment]
Hmm, it seems that the version bump breaks our "does `libbpf-rs` compile?" test:

https://github.com/libbpf/libbpf-sys/actions/runs/7660086732/job/20876617763

cc @danielocfb

**Comment by danielocfb** [comment]
Very weird. What seems to be happening here is that, because we create the test project inside the `libbpf-sys` repository, it acts as a workspace member. And then, just by virtue of adding the `libbpf-rs` dependency to it, the current version of `libbpf-sys` is queried on crates.io, presumably because it is implicitly known by virtue of being part of the workspace. Of course, because in this case this version hasn't been published yet that operation fails. I can't say that I can fully make sense of the behavior, but it's easy to work around.

**Comment by alexforster** [comment]
Ah, presumably just check it out into a subdir?

https://github.com/actions/checkout/blob/main/README.md?plain=1#L69-L70

I can do that. I'll have to rewrite master.

**Comment by danielocfb** [comment]
I just opened https://github.com/libbpf/libbpf-sys/pull/75, which should fix it as per my testing.

**Comment by alexforster** [comment]
Cool thanks, I'll get it merged.

**Comment by alexforster** [comment]
Released: https://crates.io/crates/libbpf-sys/1.3.0+v1.3.0

**Comment by danielocfb** [comment]
Thank you!

**Pull request merged**
